//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOC_TestOnline.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeThi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeThi()
        {
            this.BaiThis = new HashSet<BaiThi>();
        }
    
        public string MaDeThi { get; set; }
        public string MaNghiepVu { get; set; }
        public Nullable<int> MaCauHoi1 { get; set; }
        public Nullable<int> MaCauHoi2 { get; set; }
        public Nullable<int> MaCauHoi3 { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaiThi> BaiThis { get; set; }
        public virtual CauHoi CauHoi { get; set; }
        public virtual CauHoi CauHoi1 { get; set; }
        public virtual CauHoi CauHoi2 { get; set; }
        public virtual NghiepVu NghiepVu { get; set; }
    }
}
