//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOC_TestOnline.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KetQua
    {
        public int MaKetQua { get; set; }
        public Nullable<int> MaBaiThi { get; set; }
        public Nullable<int> DiemSo { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual BaiThi BaiThi { get; set; }
    }
}
