//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOC_TestOnline.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFullExam
    {
        public string MaDeThi { get; set; }
        public string MaNghiepVu { get; set; }
        public string TenNghiepVu { get; set; }
        public string MaDonVi { get; set; }
        public Nullable<int> MaCauHoi1 { get; set; }
        public Nullable<int> MaCauHoi2 { get; set; }
        public Nullable<int> MaCauHoi3 { get; set; }
    }
}
