//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOC_TestOnline.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFullAccountDetail
    {
        public string TenTaiKhoan { get; set; }
        public string HoTen { get; set; }
        public string TenPhong { get; set; }
        public string TenDoi { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
    }
}
