//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOC_TestOnline.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFullQuestionDetail
    {
        public int MaCauHoi { get; set; }
        public string MaNghiepVu { get; set; }
        public string TenPhong { get; set; }
        public string TenDoi { get; set; }
        public string TenNghiepVu { get; set; }
        public string CauHoi { get; set; }
        public string TraLoi1 { get; set; }
        public string TraLoi2 { get; set; }
        public string TraLoi3 { get; set; }
        public int DapAn { get; set; }
    }
}
